
[package]
name = "openzeppelin_token"
version = "0.1.0"
description = ""
homepage = ""
edition = "2023_11"

[tool]
fmt.workspace = true

[dependencies]
starknet = "2.6.4"
openzeppelin_account = { path = "../account" }
openzeppelin_introspection = { path = "../introspection" }
openzeppelin_governance = { path = "../governance" }
