
[package]
name = "openzeppelin_token"
version =  "0.15.0-rc.0"
description = ""
homepage = ""
edition = "2023_11"

[tool]
fmt.workspace = true

[dependencies]
starknet = "2.7.0-rc.3"
openzeppelin_account = { path = "../account" }
openzeppelin_introspection = { path = "../introspection" }
openzeppelin_governance = { path = "../governance" }
