version: 2
# Allow Dependabot to open PRs for security issues and general version updates.
# It checks github actions.
# Unfortunately, this is not yet possible for Scarb packages (https://github.com/software-mansion/scarb/issues/1083)
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
