comment:
  layout: "diff, files, header, footer"
  behavior: default

coverage:
  # The value range where you want the value to be green
  # Hold ourselves to a high bar.
  # TMP 80 floor until cairo-coverage becomes more stable
  range: 80..100
  status:
    project:
      coverage:
        # Use the coverage from the base commit (pull request base) coverage to compare against.
        # Once we have a baseline we can be more strict.
        # TMP threshold until cairo-coverage becomes more stable
        target: auto
        threshold: 4%
    patch:
      default:
        # Require new code to have 90%+ coverage.
        # TMP target and threshold until cairo-coverage becomes more stable
        target: 80%
        threshold: 4%

ignore:
  - "**/tests/**"
  - "docs/"
  - "scripts/"
  - "packages/test_common/"

github_checks:
  annotations: false
