pub(crate) mod src5_mocks;
pub(crate) mod account_mocks;
pub(crate) mod erc1155_mocks;
pub(crate) mod erc1155_receiver_mocks;
pub(crate) mod erc20_mocks;
pub(crate) mod erc721_mocks;
pub(crate) mod erc721_receiver_mocks;
pub(crate) mod eth_account_mocks;
pub(crate) mod non_implementing_mock;
