= Utilities

:deploy_syscall: link:https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/system-calls-cairo1/#deploy[deploy_syscall]

The following documentation provides reasoning and examples for functions and constants found in `openzeppelin::utils`
and `openzeppelin::tests::utils`.

CAUTION: Expect this module to evolve (as it has already done).

== Core utilities

[.contract]
[[utils]]
=== `++utils++`

```cairo
use openzeppelin::utils;
```

Module containing core utilities of the library.

[.contract-index]
.Members
--
.Functions
* xref:#utils-try_selector_with_fallback[`++try_selector_with_fallback(target, selector, fallback, args)++`]

.Traits
* xref:#utils-UnwrapAndCast[`++UnwrapAndCast++`]

.Inner modules
* xref:#utils-cryptography[`++cryptography++`]
* xref:#utils-deployments[`++deployments++`]
* xref:#utils-math[`++math++`]
* xref:#utils-selectors[`++selectors++`]
* xref:#utils-serde[`++serde++`]
--

[#utils-Functions]
==== Functions

[.contract-item]
[[utils-try_selector_with_fallback]]
==== `[.contract-item-name]#++try_selector_with_fallback++#++(target: ContractAddress, selector: felt252, fallback: felt252, args: Span<felt252>) → SyscallResult<Span<felt252>>++` [.item-kind]#function#

Tries to call a given selector on a given contract, and if it fails, tries to call a fallback selector.

It was designed for falling back to the `camelCase` selector for backward compatibility in the
case of a failure of the `snake_case` selector.

Returns a `SyscallResult` with the result of the successful call.

Note that:

- If the first call succeeds, the second call is not attempted.

- If the first call fails with an error different than `ENTRYPOINT_NOT_FOUND`, the error is returned
without falling back to the second selector.

- If the first call fails with `ENTRYPOINT_NOT_FOUND`, the second call is attempted, and if it fails its
error is returned.

WARNING: The fallback mechanism won't work on live chains (mainnet or testnets) until
they implement panic handling in their runtime.

[#utils-Traits]
==== Traits

[.contract-item]
[[utils-UnwrapAndCast]]
==== `[.contract-item-name]#++UnwrapAndCast++#` [.item-kind]#trait#

Trait for exposing an `unwrap_and_cast` function to `SyscallResult` objects. This may be useful
when unwrapping a syscall result to a type implementing the `Serde` trait, and you want to avoid the boilerplate of
casting and unwrapping the result multiple times.

Usage example:

```cairo
use openzeppelin::utils::selectors;
use openzeppelin::utils::UnwrapAndCast;

fn call_and_cast_to_bool(target: ContractAddress, args: Span<felt252>) -> bool {
    try_selector_with_fallback(
        target, selectors::has_role, selectors::hasRole, args
    ).unwrap_and_cast()
}

fn call_and_cast_to_felt252(target: ContractAddress, args: Span<felt252>) -> felt252 {
    try_selector_with_fallback(
        target, selectors::get_role_admin, selectors::getRoleAdmin, args
    ).unwrap_and_cast()
}
```

Note that it can be automatically casted to any type implementing the `Serde` trait.

[#utils-Inner-Modules]
==== Inner modules

[.contract-item]
[[utils-cryptography]]
==== `[.contract-item-name]#++cryptography++#` [.item-kind]#module#

See xref:#cryptography[`openzeppelin::utils::cryptography`].

[.contract-item]
[[utils-deployments]]
==== `[.contract-item-name]#++deployments++#` [.item-kind]#module#

See xref:#deployments[`openzeppelin::utils::deployments`].

[.contract-item]
[[utils-math]]
==== `[.contract-item-name]#++math++#` [.item-kind]#module#

See xref:#math[`openzeppelin::utils::math`].

[.contract-item]
[[utils-selectors]]
==== `[.contract-item-name]#++selectors++#` [.item-kind]#module#

See xref:#selectors[`openzeppelin::utils::selectors`].

[.contract-item]
[[utils-serde]]
==== `[.contract-item-name]#++serde++#` [.item-kind]#module#

See xref:#serde[`openzeppelin::utils::serde`].

[.contract]
[[cryptography]]
=== `++cryptography++`

:snip12: https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md[SNIP12]

```cairo
use openzeppelin::utils::cryptography;
```

Module containing utilities related to cryptography.

[.contract-index]
.Members
--
.Inner modules
* xref:#cryptography-nonces[`++nonces++`]
* xref:#cryptography-snip12[`++snip12++`]
--

[#cryptography-Inner modules]
==== Inner modules

[.contract-item]
[[cryptography-nonces]]
==== `[.contract-item-name]#++nonces++#` [.item-kind]#module#

See xref:#NoncesComponent[`openzeppelin::utils::cryptography::nonces::NoncesComponent`].

[.contract-item]
[[cryptography-snip12]]
==== `[.contract-item-name]#++snip12++#` [.item-kind]#module#

See xref:#snip12[`openzeppelin::utils::cryptography::snip12`].

[.contract]
[[deployments]]
=== `++deployments++`

:udc-doc: xref:/udc.adoc[Universal Deployer Contract]

```cairo
use openzeppelin::utils::deployments;
```

Module containing utility functions for calculating contract addresses through {deploy_syscall} and the {udc-doc} (UDC).

[.contract-index]
.Members
--
.Structs
* xref:deployments-DeployerInfo[`++DeployerInfo(caller_address, udc_address)++`]

.Functions
* xref:deployments-calculate_contract_address_from_deploy_syscall[`++calculate_contract_address_from_deploy_syscall(salt, class_hash, constructor_calldata, deployer_address)++`]
* xref:deployments-compute_hash_on_elements[`++compute_hash_on_elements(data)++`]
* xref:deployments-calculate_contract_address_from_udc[`++calculate_contract_address_from_udc(salt, class_hash, constructor_calldata, deployer_info)++`]
--

[#deployments-Structs]
==== Structs

:calculate_contract_address_from_udc: xref:deployments-calculate_contract_address_from_udc[utils::calculate_contract_address_from_udc]

[.contract-item]
[[deployments-DeployerInfo]]
==== `[.contract-item-name]#++DeployerInfo++#++(caller_address: ContractAddress, udc_address: ContractAddress)++` [.item-kind]#struct#

Struct containing arguments necessary in {calculate_contract_address_from_udc} for origin-dependent deployment calculations.

[#deployments-Functions]
==== Functions

:deployer-info: xref:deployments-DeployerInfo[DeployerInfo]

[.contract-item]
[[deployments-calculate_contract_address_from_deploy_syscall]]
==== `[.contract-item-name]#++calculate_contract_address_from_deploy_syscall++#++(salt: felt252, class_hash: ClassHash, constructor_calldata: Span<felt252>, deployer_address: ContractAddress) → ContractAddress++` [.item-kind]#function#

Returns the contract address when passing the given arguments to {deploy_syscall}.

[.contract-item]
[[deployments-compute_hash_on_elements]]
==== `[.contract-item-name]#++compute_hash_on_elements++#++(mut data: Span<felt252>) → felt252++` [.item-kind]#function#

Creates a Pedersen hash chain with the elements of `data` and returns the finalized hash.

[.contract-item]
[[deployments-calculate_contract_address_from_udc]]
==== `[.contract-item-name]#++calculate_contract_address_from_udc++#++(salt: felt252, class_hash: ClassHash, constructor_calldata: Span<felt252>, deployer_info: Option<DeployerInfo>) → ContractAddress++` [.item-kind]#function#

Returns the calculated contract address for UDC deployments.

Origin-independent deployments (deployed from zero) should pass `Option::None` as `deployer_info`.

Origin-dependent deployments hash `salt` with `caller_address` (member of {deployer-info}) and pass the hashed salt to the inner {deploy_syscall} as the `contract_address_salt` argument.

[.contract]
[[math]]
=== `++math++`

```cairo
use openzeppelin::utils::math;
```

Module containing math utilities.

[.contract-index]
.Members
--
.Functions
* xref:#math-average[`++average(a, b)++`]
--

[#math-Functions]
==== Functions

[.contract-item]
[[math-average]]
==== `[.contract-item-name]#++average++#++(a: T, b: T) → T++` [.item-kind]#function#

Returns the average of two values. The result is rounded down.

NOTE: `T` is a generic value matching different numeric implementations.

[.contract]
[[selectors]]
=== `++selectors++`

```cairo
use openzeppelin::utils::selectors;
```

:selectors: https://github.com/OpenZeppelin/cairo-contracts/blob/release-v0.12.0/src/utils/selectors.cairo[selectors.cairo]

Module containing constants matching multiple selectors used through the library.
To see the full list of selectors, see {selectors}.

[.contract]
[[serde]]
=== `++serde++`

```cairo
use openzeppelin::utils::serde;
```

Module containing utilities related to serialization and deserialization of Cairo data structures.

[.contract-index]
.Members
--
.Traits
* xref:#serde-SerializedAppend[`++SerializedAppend++`]
--

[#serde-Traits]
==== Traits

[.contract-item]
[[serde-SerializedAppend]]
==== `[.contract-item-name]#++SerializedAppend++#` [.item-kind]#trait#

Importing this trait allows the ability to append a serialized representation of a Cairo data structure already
implementing the `Serde` trait to a `felt252` buffer.

Usage example:

```cairo
use openzeppelin::utils::serde::SerializedAppend;
use starknet::ContractAddress;

fn to_calldata(recipient: ContractAddress, amount: u256) -> Array<felt252> {
    let mut calldata = array![];
    calldata.append_serde(recipient);
    calldata.append_serde(amount);
    calldata
}
```

Note that the `append_serde` method is automatically available for arrays of felts, and it accepts any data structure
that implements the `Serde` trait.

== Cryptography

[.contract]
[[NoncesComponent]]
=== `++NoncesComponent++`

```cairo
use openzeppelin::utils::cryptography::nonces::NoncesComponent;
```

Simple component for managing nonces.

[.contract-index#NoncesComponent-Embeddable-Impls]
.Embeddable Implementations
--
[.sub-index#NoncesComponent-Embeddable-Impls-NoncesImpl]
.NoncesImpl

* xref:#NoncesComponent-nonces[`++nonces(self, owner)++`]
--

[.contract-index]
.Internal Implementations
--
.InternalImpl

* xref:#NoncesComponent-use_nonce[`++use_nonce(self, owner)++`]
* xref:#NoncesComponent-use_checked_nonce[`++use_checked_nonce(self, owner, nonce)++`]
--

[#NoncesComponent-Embeddable-Functions]
==== Embeddable functions

[.contract-item]
[[NoncesComponent-nonces]]
==== `[.contract-item-name]#++nonces++#++(self: @ContractState, owner: ContractAddress) → felt252++` [.item-kind]#external#

Returns the next unused nonce for an `owner`.

[#NoncesComponent-Internal-Functions]
==== Internal functions

[.contract-item]
[[NoncesComponent-use_nonce]]
==== `[.contract-item-name]#++use_nonce++#++(ref self: ComponentState, owner: ContractAddress) → felt252++` [.item-kind]#internal#

Consumes a nonce, returns the current value, and increments nonce.

For each account, the nonce has an initial value of 0, can only be incremented by one, and cannot be
decremented or reset. This guarantees that the nonce never overflows.

[.contract-item]
[[NoncesComponent-use_checked_nonce]]
==== `[.contract-item-name]#++use_checked_nonce++#++(ref self: ComponentState, owner: ContractAddress, nonce: felt252) → felt252++` [.item-kind]#internal#

Same as `use_nonce` but checking that `nonce` is the next valid one for `owner`.

[.contract]
[[snip12]]
=== `++snip12++`

```cairo
use openzeppelin::utils::snip12;
```

Supports on-chain generation of message hashes compliant with {snip12}.

NOTE: For a full walkthrough on how to use this module, see the
xref:/guides/snip12.adoc[SNIP12 and Typed Messages] guide.

== Test utilities

[.contract]
[[testutils]]
=== `++utils++`

```cairo
use openzeppelin::tests::utils;
```

Module containing utilities for testing the library.

[.contract-index]
.Members
--
.Functions
* xref:#testutils-deploy[`++deploy(contract_class_hash, calldata)++`]
* xref:#testutils-deploy_with_salt[`++deploy_with_salt(contract_class_hash, calldata, salt)++`]
* xref:#testutils-pop_log[`++pop_log<T>(address)++`]
* xref:#testutils-assert_indexed_keys[`++assert_indexed_keys<T>(event, expected_keys)++`]
* xref:#testutils-assert_no_events_left[`++assert_no_events_left(address)++`]
* xref:#testutils-drop_event[`++drop_event(address)++`]
* xref:#testutils-drop_events[`++drop_events(address, n_events)++`]

.Inner modules
* xref:#testutils-constants[`++constants++`]
--

[#testutils-Functions]
==== Functions

[.contract-item]
[[testutils-deploy]]
==== `[.contract-item-name]#++deploy++#++(contract_class_hash: felt252, calldata: Array<felt252>) → ContractAddress++` [.item-kind]#function#

Uses the `{deploy_syscall}` to deploy an instance of the contract given the class hash and the calldata.

The `contract_address_salt` is always set to zero, and `deploy_from_zero` is set to false.

Usage example:

```cairo
use openzeppelin::presets::AccountUpgradeable;
use openzeppelin::tests::utils;
use starknet::ContractAddress;

const PUBKEY: felt252 = 'PUBKEY';

fn deploy_test_contract() -> ContractAddress {
    let calldata = array![PUBKEY];
    utils::deploy(AccountUpgradeable::TEST_CLASS_HASH, calldata)
}
```

[.contract-item]
[[testutils-deploy_with_salt]]
==== `[.contract-item-name]#++deploy_with_salt++#++(contract_class_hash: felt252, calldata: Array<felt252>, salt: felt252) → ContractAddress++` [.item-kind]#function#

:deploy: xref:testutils-deploy[utils::deploy]

Same as {deploy} except this function accepts a `salt` argument.
This utility is useful when tests require multiple deployed instances of the same contract.

[.contract-item]
[[testutils-pop_log]]
==== `[.contract-item-name]#++pop_log++#++<T>(address: ContractAddress) → Option<T>++` [.item-kind]#function#

Pops the earliest unpopped logged event for the contract as the requested type
and checks that there's no more keys or data left on the event, preventing unaccounted params.

Required traits for `T`:

- `Drop`
- `starknet::Event`

Requirements:

- No extra data or keys are left on the raw event after deserialization.

Usage example:

```cairo
use openzeppelin::tests::utils;
use openzeppelin::token::erc20::ERC20Component;
use openzeppelin::token::erc20::ERC20Component::Transfer;
use starknet::ContractAddress;

fn assert_emitted_event(
    target: ContractAddress, from: ContractAddress, to: ContractAddress, value: u256
) {
    let event = utils::pop_log::<ERC20Component::Event>(target).unwrap();
    let expected = ERC20Component::Event::Transfer(Transfer { from, to, value });
    assert!(event == expected);
}
```

[.contract-item]
[[testutils-assert_indexed_keys]]
==== `[.contract-item-name]#++assert_indexed_keys++#<T>(event: T, expected_keys: Span<felt252>)` [.item-kind]#function#

Asserts that `expected_keys` exactly matches the indexed keys from `event`.

`expected_keys` must include all indexed event keys for `event` in the order
that they're defined.

NOTE: If the event is not flattened, the first key will be the event member name
e.g. `selector!("EnumMemberName")`.

Required traits for `T`:

- `Drop`
- `starknet::Event`

[.contract-item]
[[testutils-assert_no_events_left]]
==== `[.contract-item-name]#++assert_no_events_left++#++(address: ContractAddress)++` [.item-kind]#function#

Asserts that there are no more events left in the queue for the given address.

[.contract-item]
[[testutils-drop_event]]
==== `[.contract-item-name]#++drop_event++#++(address: ContractAddress)++` [.item-kind]#function#

Removes an event from the queue for the given address.

If the queue is empty, this function won't do anything.

[.contract-item]
[[testutils-drop_events]]
==== `[.contract-item-name]#++drop_events++#++(address: ContractAddress, n_events: felt252)++` [.item-kind]#function#

Removes `n_events` from the queue for the given address.

If the queue is empty, this function won't do anything.

[#testutils-Inner-Modules]
==== Inner modules

[.contract-item]
[[testutils-constants]]
==== `[.contract-item-name]#++constants++#` [.item-kind]#module#

See xref:#constants[`openzeppelin::tests::utils::constants`].

[.contract]
[[constants]]
=== `++constants++`

```cairo
use openzeppelin::tests::utils::constants;
```

:constants: https://github.com/OpenZeppelin/cairo-contracts/blob/release-v0.12.0/src/tests/utils/constants.cairo[constants.cairo]

Module containing constants that are repeatedly used among tests.
To see the full list, see {constants}.
