= Extensibility

Smart contract development is a critical task.
As with all software development, it is error prone;
but unlike most scenarios, a bug can result in major losses for organizations as well as individuals.
Therefore, writing complex smart contracts is a delicate task.

One of the best approaches to minimize introducing bugs is to reuse existing, battle-tested code.
Starknet uses components to allow developers to easily integrate extensible code into their contracts.

== Components

Starknet components are separate modules that contain storage, events, and external functions that can be integrated into a contract.
Components themselves cannot be declared or deployed.
Another way to think of components is that they are abstract modules that must be instantiated.

== Integrating components


Component integration requires the following steps:

1. Declare the component with `component!`
2. Add the component's storage and events to the contract's `Storage` and `Event` types.
3. Bring the requisite implementations into scope
