:starknet: https://starkware.co/product/starknet/[Starknet]
:scarb: https://docs.swmansion.com/scarb[Scarb]
:installation: https://docs.swmansion.com/scarb/download.html[this guide]

= Contracts for Cairo

include::./utils/_common.adoc[]

*A library for secure smart contract development* written in Cairo for {starknet}. This library consists of a set of xref:components.adoc[reusable components] to build custom smart contracts, as well as
ready-to-deploy xref:presets.adoc[presets]. You can also find other xref:/api/utilities.adoc[utilities] including xref:interfaces.adoc[interfaces and dispatchers] and xref:/api/testing.adoc[test utilities]
that facilitate testing with Starknet Foundry.

WARNING: This repo contains highly experimental code. Expect rapid iteration. *Use at your own risk.*

NOTE: You can track our roadmap and future milestones in our https://github.com/orgs/OpenZeppelin/projects/29/[Github Project].

== Installation

The library is available as a {scarb} package. Follow {installation} for installing Cairo and Scarb on your machine
before proceeding, and run the following command to check that the installation was successful:

[,bash]
----
$ scarb --version

scarb 2.13.1 (dc0dbfd50 2025-09-15)
cairo: 2.13.1 (https://crates.io/crates/cairo-lang-compiler/2.13.1)
sierra: 1.7.0
----

=== Set up your project

Create an empty directory, and `cd` into it:

[,bash]
----
mkdir my_project/ && cd my_project/
----

Initialize a new Scarb project:

[,bash]
----
scarb init
----

The contents of `my_project/` should now look like this:

[,bash]
----
$ ls

Scarb.toml src
----

=== Install the library

:versioning: xref:index.adoc#versioning_of_the_sub_packages[Versioning of the sub-packages]

[IMPORTANT]
====
The `openzeppelin` package is an umbrella (meta) package that aggregates all library subpackages. Prior to v3.x, the umbrella and its subpackages were
versioned in lockstep—their versions always matched. Starting with v3.x, following the introduction of `openzeppelin_interfaces`, the umbrella is
versioned independently from some of the subpackages.

See the {versioning} section for more information.
====

Install the library by declaring it as a dependency in the project's `Scarb.toml` file:

[,javascript]
----
[dependencies]
openzeppelin = "3.0.0-alpha.3"
----

The previous example would import the entire library. We can also add each package as a separate dependency to
improve the building time by not including modules that won't be used:

[,javascript,subs=+attributes]
----
[dependencies]
openzeppelin_access = "3.0.0-alpha.3"
openzeppelin_token = "3.0.0-alpha.3"
openzeppelin_interfaces = "{current_openzeppelin_interfaces_version}"
----

== Versioning of the sub-packages

Here you can find a reference of the versioning of the sub-packages for this umbrella version:

[,javascript,subs=+attributes]
----
[dependencies]
openzeppelin_access = "3.0.0-alpha.3"
openzeppelin_token = "3.0.0-alpha.3"
openzeppelin_access = "3.0.0-alpha.3"
openzeppelin_account = "3.0.0-alpha.3"
openzeppelin_finance = "3.0.0-alpha.3"
openzeppelin_interfaces = "{current_openzeppelin_interfaces_version}"
openzeppelin_governance = "3.0.0-alpha.3"
openzeppelin_introspection = "3.0.0-alpha.3"
openzeppelin_merkle_tree = "3.0.0-alpha.3"
openzeppelin_presets = "3.0.0-alpha.3"
openzeppelin_security = "3.0.0-alpha.3"
openzeppelin_token = "3.0.0-alpha.3"
openzeppelin_upgrades = "3.0.0-alpha.3"

openzeppelin_interfaces = "{current_openzeppelin_interfaces_version}"
openzeppelin_utils = "{current_openzeppelin_utils_version}"
----

== Basic usage

This is how it looks to build an ERC20 contract using the xref:erc20.adoc[ERC20 component].
Copy the code into `src/lib.cairo`.

[,cairo]
----
#[starknet::contract]
mod MyERC20Token {
    // NOTE: If you added the entire library as a dependency,
    // use `openzeppelin::token` instead.
    use openzeppelin_token::erc20::{ERC20Component, ERC20HooksEmptyImpl, DefaultConfig};
    use starknet::ContractAddress;

    component!(path: ERC20Component, storage: erc20, event: ERC20Event);

    // ERC20 Mixin
    #[abi(embed_v0)]
    impl ERC20MixinImpl = ERC20Component::ERC20MixinImpl<ContractState>;
    impl ERC20InternalImpl = ERC20Component::InternalImpl<ContractState>;

    #[storage]
    struct Storage {
        #[substorage(v0)]
        erc20: ERC20Component::Storage
    }

    #[event]
    #[derive(Drop, starknet::Event)]
    enum Event {
        #[flat]
        ERC20Event: ERC20Component::Event
    }

    #[constructor]
    fn constructor(
        ref self: ContractState,
        name: ByteArray,
        symbol: ByteArray,
        fixed_supply: u256,
        recipient: ContractAddress
    ) {
        self.erc20.initializer(name, symbol);
        self.erc20.mint(recipient, fixed_supply);
    }
}
----

You can now compile it:

[,bash]
----
scarb build
----
