:starknet: https://starkware.co/product/starknet/[Starknet]
:scarb: https://docs.swmansion.com/scarb[Scarb]
:installation: https://docs.swmansion.com/scarb/download.html[this guide]

= Contracts for Cairo

*A library for secure smart contract development* written in Cairo for {starknet}, a decentralized ZK Rollup.

WARNING: This repo contains highly experimental code. Expect rapid iteration. *Use at your own risk.*

NOTE: You can track our roadmap and future milestones in our https://github.com/orgs/OpenZeppelin/projects/29/[Github Project].

== Installation

The library is available as a {scarb} package. Follow {installation} for installing Cairo and Scarb on your machine
before proceeding, and run the following command to check that the installation was successful:

[,bash]
----
$ scarb --version

scarb 2.3.0 (f306f9a91 2023-10-23)
cairo: 2.3.0 (https://crates.io/crates/cairo-lang-compiler/2.3.0)
sierra: 1.3.0
----

=== Set up your project

Create an empty directory, and `cd` into it:

[,bash]
----
mkdir my_project/ && cd my_project/
----

Initialize a new Scarb project:

[,bash]
----
scarb init
----

The contents of `my_project/` should now look like this:

[,bash]
----
$ ls

Scarb.toml src
----

=== Install the library

Install the library by declaring it as a dependency in the project's `Scarb.toml` file:

[,text]
----
[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0-beta.0" }
----

WARNING: Make sure the tag matches the target release.

== Basic usage

This is how it looks to build an account contract using the xref:accounts.adoc[account] component.
Copy the code into `src/lib.cairo`.

[,javascript]
----
#[starknet::contract]
mod MyAccount {
    use openzeppelin::account::Account as account_component;
    use openzeppelin::introspection::src5::SRC5 as src5_component;

    component!(path: account_component, storage: account, event: AccountEvent);
    component!(path: src5_component, storage: src5, event: SRC5Event);

    /// Account
    #[abi(embed_v0)]
    impl SRC6Impl = account_component::SRC6Impl<ContractState>;
    #[abi(embed_v0)]
    impl SRC6CamelOnlyImpl = account_component::SRC6CamelOnlyImpl<ContractState>;
    #[abi(embed_v0)]
    impl DeclarerImpl = account_component::DeclarerImpl<ContractState>;
    #[abi(embed_v0)]
    impl DeployableImpl = account_component::DeployableImpl<ContractState>;
    impl AccountInternalImpl = account_component::InternalImpl<ContractState>;

    /// SRC5
    #[abi(embed_v0)]
    impl SRC5Impl = src5_component::SRC5Impl<ContractState>;


    #[storage]
    struct Storage {
        #[substorage(v0)]
        account: account_component::Storage,
        #[substorage(v0)]
        src5: src5_component::Storage
    }

    #[event]
    #[derive(Drop, starknet::Event)]
    enum Event {
        #[flat]
        AccountEvent: account_component::Event,
        #[flat]
        SRC5Event: src5_component::Event
    }

    #[constructor]
    fn constructor(ref self: ContractState, public_key: felt252) {
        self.account.initializer(public_key);
    }
}
----

You can now compile it:

[,bash]
----
scarb build
----