:account: xref:/api/account.adoc#Account[Account]
:eth-account-upgradeable: xref:/api/account.adoc#EthAccountUpgradeable[EthAccountUpgradeable]
:erc20: xref:/api/erc20.adoc#ERC20[ERC20]
:erc721: xref:/api/erc721.adoc#ERC721[ERC721]
:sierra-class-hashes: https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/class-hash[Sierra class hashes]
:starkli: https://book.starkli.rs/introduction[starkli]
:wizard: https://wizard.openzeppelin.com[Wizard for Cairo]


= Presets

include::utils/_class_hashes.adoc[]

Presets are ready-to-deploy contracts provided by the library. Since presets are intended to be very simple
and as generic as possible, there's no support for custom or complex contracts such as `ERC20Pausable` or `ERC721Mintable`.

TIP: For contract customization and combination of modules you can use {wizard}, our code-generation tool.


## Available presets

List of available presets and their corresponding {sierra-class-hashes}.

NOTE: Class hashes were computed using {class-hash-cairo-version}.

|===
| Name | Sierra Class Hash

| `{account}`
| `{Account-class-hash}`

| `{eth-account-upgradeable}`
| `{EthAccountUpgradeable-class-hash}`

| `{erc20}`
| `{ERC20-class-hash}`

| `{erc721}`
| `{ERC721-class-hash}`
|===

TIP: {starkli} class-hash command can be used to compute the class hash from a compiled artifact.
