= Utilities

The following documentation provides reasoning and examples for functions and constants found in `openzeppelin::utils`
and `openzeppelin::tests::utils`.

CAUTION: Expect this module to evolve (as it has already done).

== Core utilities

[.contract]
[[utils]]
=== `++utils++`

```javascript
use openzeppelin::utils;
```

Module containing core utilities of the library.

[.contract-index]
.Members
--
.Functions
* xref:#utils-try_selector_with_fallback[`++try_selector_with_fallback(target, selector, fallback, args)++`]

.Traits
* xref:#utils-UnwrapAndCast[`++UnwrapAndCast++`]

.Inner modules
* xref:#utils-selectors[`++selectors++`]
* xref:#utils-serde[`++serde++`]
* xref:#utils-universal_deployer[`++universal_deployer++`]
--

[#utils-Functions]
==== Functions

[.contract-item]
[[utils-try_selector_with_fallback]]
==== `[.contract-item-name]#++try_selector_with_fallback++#++(target: ContractAddress, selector: felt252, fallback: felt252, args: Span<felt252>) → SyscallResult<Span<felt252>>++` [.item-kind]#function#

Tries to call a given selector on a given contract, and if it fails, tries to call a fallback selector.

It was designed for falling back to the `camelCase` selector for backward compatibility in the
case of a failure of the `snake_case` selector.

Returns a `SyscallResult` with the result of the successful call.

Note that:

- If the first call succeeds, the second call is not attempted.

- If the first call fails with an error different than `ENTRYPOINT_NOT_FOUND`, the error is returned
without falling back to the second selector.

- If the first call fails with `ENTRYPOINT_NOT_FOUND`, the second call is attempted, and if it fails its
error is returned.

WARNING: The fallback mechanism won't work on live chains (mainnet or testnets) until
they implement panic handling in their runtime.

[#utils-Traits]
==== Traits

[.contract-item]
[[utils-UnwrapAndCast]]
==== `[.contract-item-name]#++UnwrapAndCast++#` [.item-kind]#trait#

Trait for exposing an `unwrap_and_cast` function to `SyscallResult` objects. This may be useful
when unwrapping a syscall result to a type implementing the `Serde` trait, and you want to avoid the boilerplate of
casting and unwrapping the result multiple times.

Usage example:

```javascript
use openzeppelin::utils::selectors;
use openzeppelin::utils::UnwrapAndCast;

fn call_and_cast_to_bool(target: ContractAddress, args: Span<felt252>) -> bool {
    try_selector_with_fallback(
        target, selectors::has_role, selectors::hasRole, args
    ).unwrap_and_cast()
}

fn call_and_cast_to_felt252(target: ContractAddress, args: Span<felt252>) -> felt252 {
    try_selector_with_fallback(
        target, selectors::get_role_admin, selectors::getRoleAdmin, args
    ).unwrap_and_cast()
}
```

Note that it can be automatically casted to any type implementing the `Serde` trait.

[#utils-Inner-Modules]
==== Inner modules

[.contract-item]
[[utils-selectors]]
==== `[.contract-item-name]#++selectors++#` [.item-kind]#module#

See xref:#selectors[`openzeppelin::utils::selectors`].

[.contract-item]
[[utils-serde]]
==== `[.contract-item-name]#++serde++#` [.item-kind]#module#

See xref:#serde[`openzeppelin::utils::serde`].

[.contract]
[[selectors]]
=== `++selectors++`

```javascript
use openzeppelin::utils::selectors;
```

:selectors: https://github.com/OpenZeppelin/cairo-contracts/blob/release-v0.10.0/src/utils/selectors.cairo[selectors.cairo]

Module containing constants matching multiple selectors used through the library.
To see the full list of selectors, see {selectors}.

[.contract]
[[serde]]
=== `++serde++`

```javascript
use openzeppelin::utils::serde;
```

Module containing utilities related to serialization and deserialization of Cairo data structures.

[.contract-index]
.Members
--
.Traits
* xref:#serde-SerializedAppend[`++SerializedAppend++`]
--

[#serde-Traits]
==== Traits

[.contract-item]
[[serde-SerializedAppend]]
==== `[.contract-item-name]#++SerializedAppend++#` [.item-kind]#trait#

Importing this trait allows the ability to append a serialized representation of a Cairo data structure already
implementing the `Serde` trait to a `felt252` buffer.

Usage example:

```javascript
use openzeppelin::utils::serde::SerializedAppend;
use starknet::ContractAddress;

fn to_calldata(recipient: ContractAddress, amount: u256) -> Array<felt252> {
    let mut calldata = array![];
    calldata.append_serde(recipient);
    calldata.append_serde(amount);
    calldata
}
```

Note that the `append_serde` method is automatically available for arrays of felts, and it accepts any data structure
that implements the `Serde` trait.

[.contract]
[[utils-universal_deployer]]
=== `++universal_deployer++`

:udc-doc: xref:/udc.adoc[Universal Deployer Contract]

```javascript
use openzeppelin::utils::universal_deployer;
```
Module containing the Universal Deployer interface and utility functions for calculating contract addresses through the {udc-doc} (UDC).

[.contract-index]
.Members
--
.Interface
* xref:#universal_deployer-IUniversalDeployer[`++IUniversalDeployer++`]

.Functions
* xref:universal_deployer-calculate_contract_address_from_zero[`++calculate_contract_address_from_zero++`]
* xref:universal_deployer-calculate_contract_address_not_from_zero[`++calculate_contract_address_not_from_zero++`]
* xref:universal_deployer-compute_hash_on_elements[`++compute_hash_on_elements++`]
* xref:universal_deployer-_calculate_contract_address_from_hash[`++_calculate_contract_address_from_hash++`]
--

[#universal_deployer-Interface]
==== Interface

:udc-api: xref:/api/udc.adoc[Universal Deployer API]
:cairo-calculate-fn: link:https://github.com/starkware-libs/cairo/blob/v2.6.3/crates/cairo-lang-runner/src/casm_run/contract_address.rs#L38-L57[calculate_contract_address]

[.contract-item]
[[universal_deployer-IUniversalDeployer]]
==== `[.contract-item-name]#++IUniversalDeployer++#` [.item-kind]#interface#

Interface for the Universal Deployer Contract (UDC).

See the {udc-api} page for the specification.

[#universal_deployer-Functions]
==== Functions

:udc-deploy_contract: xref:/api/udc.adoc#UniversalDeployer-deploy_contract[UniversalDeployer::deploy_contract]

[.contract-item]
[[universal_deployer-calculate_contract_address_from_zero]]
==== `[.contract-item-name]#++calculate_contract_address_from_zero++#++(salt: felt252, class_hash: ClassHash, constructor_calldata: Span<felt252>) → ContractAddress++` [.item-kind]#function#

Returns the calculated address for origin-independent deployments (when `from_zero` is `true` in {udc-deploy_contract}).

[.contract-item]
[[universal_deployer-calculate_contract_address_not_from_zero]]
==== `[.contract-item-name]#++calculate_contract_address_not_from_zero++#++(salt: felt252, class_hash: ClassHash, constructor_calldata: Span<felt252>, caller_address: ContractAddress, deployer_address: ContractAddress) → ContractAddress++` [.item-kind]#function#

Returns the calculated address for origin-dependent deployments (when the `from_zero` argument is `false` in {udc-deploy_contract}).

This function hashes the `salt` with `caller_address` and passes the hashed salt to xref:universal_deployer-_calculate_contract_address_from_hash[_calculate_contract_address_from_hash].

[.contract-item]
[[universal_deployer-compute_hash_on_elements]]
==== `[.contract-item-name]#++compute_hash_on_elements++#++(mut data: Span<felt252>) → felt252++` [.item-kind]#function#

Creates a Pedersen hash chain with the elements of `data` and returns the finalized hash.

[.contract-item]
[[universal_deployer-_calculate_contract_address_from_hash]]
==== `[.contract-item-name]#++_calculate_contract_address_from_hash++#++(salt: felt252, class_hash: ClassHash, constructor_calldata: Span<felt252>, deployer_address: ContractAddress) → ContractAddress++` [.item-kind]#function#

Creates a Pedersen hash chain that mirrors `{cairo-calculate-fn}` written in Rust.

== Test utilities

[.contract]
[[testutils]]
=== `++utils++`

```javascript
use openzeppelin::tests::utils;
```

Module containing utilities for testing the library.

[.contract-index]
.Members
--
.Functions
* xref:#testutils-deploy[`++deploy(contract_class_hash, calldata)++`]
* xref:#testutils-pop_log[`++pop_log<T>(address)++`]
* xref:#testutils-assert_indexed_keys[`++assert_indexed_keys<T>(event, expected_keys)++`]
* xref:#testutils-assert_no_events_left[`++assert_no_events_left(address)++`]
* xref:#testutils-drop_event[`++drop_event(address)++`]

.Inner modules
* xref:#testutils-constants[`++constants++`]
--

[#testutils-Functions]
==== Functions

[.contract-item]
[[testutils-deploy]]
==== `[.contract-item-name]#++deploy++#++(contract_class_hash: felt252, calldata: Array<felt252>) → ContractAddress++` [.item-kind]#function#

:deploy_syscall: https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/system-calls/#deploy[deploy_syscall]

Uses the `{deploy_syscall}` to deploy an instance of the contract given the class hash and the calldata.

The `contract_address_salt` is always set to zero, and `deploy_from_zero` is set to false.

Usage example:

```javascript
use openzeppelin::presets::Account;
use openzeppelin::tests::utils;
use starknet::ContractAddress;

const PUBKEY: felt252 = 'PUBKEY';

fn deploy_test_contract() -> ContractAddress {
    let calldata = array![PUBKEY];
    utils::deploy(Account::TEST_CLASS_HASH, calldata)
}
```

[.contract-item]
[[testutils-pop_log]]
==== `[.contract-item-name]#++pop_log++#++<T>(address: ContractAddress) → Option<T>++` [.item-kind]#function#

Pops the earliest unpopped logged event for the contract as the requested type
and checks that there's no more keys or data left on the event, preventing unaccounted params.

Required traits for `T`:

- `Drop`
- `starknet::Event`

Requirements:

- No extra data or keys are left on the raw event after deserialization.

WARNING: This method doesn't currently work for component events that are not flattened
because an extra key is added, pushing the event ID key to the second position.

[.contract-item]
[[testutils-assert_indexed_keys]]
==== `[.contract-item-name]#++assert_indexed_keys++#<T>(event: T, expected_keys: Span<felt252>)` [.item-kind]#function#

Asserts that `expected_keys` exactly matches the indexed keys from `event`.

`expected_keys` must include all indexed event keys for `event` in the order
that they're defined.

NOTE: If the event is not flattened, the first key will be the event member name
e.g. selector!("EnumMemberName").

Required traits for `T`:

- `Drop`
- `starknet::Event`

[.contract-item]
[[testutils-assert_no_events_left]]
==== `[.contract-item-name]#++assert_no_events_left++#++(address: ContractAddress)++` [.item-kind]#function#

Asserts that there are no more events left in the queue for the given address.

[.contract-item]
[[testutils-drop_event]]
==== `[.contract-item-name]#++drop_event++#++(address: ContractAddress)++` [.item-kind]#function#

Removes an event from the queue for the given address.

If the queue is empty, this function won't do anything.

[#testutils-Inner-Modules]
==== Inner modules

[.contract-item]
[[testutils-constants]]
==== `[.contract-item-name]#++constants++#` [.item-kind]#module#

See xref:#constants[`openzeppelin::tests::utils::constants`].

[.contract]
[[constants]]
=== `++constants++`

```javascript
use openzeppelin::tests::utils::constants;
```

:constants: https://github.com/OpenZeppelin/cairo-contracts/blob/release-v0.10.0/src/tests/utils/constants.cairo[constants.cairo]

Module containing constants that are repeatedly used among tests.
To see the full list, see {constants}.
