
[package]
name = "openzeppelin_merkle_tree"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true

[tool]
fmt.workspace = true

[dev-dependencies]
assert_macros.workspace = true
starknet.workspace = true
snforge_std.workspace = true
