[package]
name = "openzeppelin_test_common"
readme = "README.md"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true

[tool]
fmt.workspace = true
scarb.workspace = true

[dependencies]
starknet.workspace = true
snforge_std.workspace = true
openzeppelin_access = { version = "4.0.1", path = "../access" }
openzeppelin_account = { version = "4.0.1", path = "../account" }
openzeppelin_finance = { version = "4.0.1", path = "../finance" }
openzeppelin_governance = { version = "4.0.1", path = "../governance" }
openzeppelin_interfaces = { version = "2.2.0", path = "../interfaces" }
openzeppelin_introspection = { version = "4.0.1", path = "../introspection" }
openzeppelin_macros = { path = "../macros" }
openzeppelin_security = { version = "4.0.1", path = "../security" }
openzeppelin_token = { version = "4.0.1", path = "../token" }
openzeppelin_testing = { path = "../testing" }
openzeppelin_upgrades = { version = "4.0.1", path = "../upgrades" }
openzeppelin_utils = { version = "2.2.0", path = "../utils" }

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true # Required for benchmarking
