[package]
name = "openzeppelin_account"
version =  "0.15.0-rc.0"
edition = "2023_11"

[tool]
fmt.workspace = true

[dependencies]
starknet = "2.7.0-rc.3"
openzeppelin_introspection = { path = "../introspection" }
openzeppelin_utils = { path = "../utils" }
