
[package]
name = "openzeppelin_utils"
version = "2.1.0-alpha.0"
readme = "README.md"
keywords = [
    "openzeppelin",
    "starknet",
    "contracts",
    "standards",
    "utils"
]
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
license-file.workspace = true

[tool]
fmt.workspace = true
scarb.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin_interfaces = { path = "../interfaces" }

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true
openzeppelin_testing = { path = "../testing" }
openzeppelin_test_common = { path = "../test_common" }

[features]
fuzzing = []

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false

[[test]]
name = "openzeppelin_utils_unittest"
build-external-contracts = [
    "openzeppelin_test_common::mocks::account::DualCaseAccountMock",
]
