name: Check for typos

on: [pull_request]

jobs:
  check-for-typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Check for typos
        uses: crate-ci/typos@631208b7aac2daa8b707f55e7331f9112b0e062d
