name: Check for typos

on: [pull_request]

jobs:
  check-for-typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Check for typos
        uses: crate-ci/typos@7c572958218557a3272c2d6719629443b5cc26fd
