name: Check for typos

on: [pull_request]

jobs:
  check-for-typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Check for typos
        uses: crate-ci/typos@aca895bf05aec0cb7dffa6f94495e923224d9f17
