name: Bump version

on:
  push:
    tags:
    - "v*"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get commits
      id: commits
      run: |
        echo "MAIN=$(git show -s --format="%H" origin/main)" >> "$GITHUB_OUTPUT"
        echo "TAG=$(git rev-list -n 1 "${GITHUB_REF#refs/*/}")" >> "$GITHUB_OUTPUT"
    - name: Print commits
      run: |
        echo "Main commit: ${{ steps.commits.outputs.MAIN }}"
        echo "Tag commit: ${{ steps.commits.outputs.TAG }}"
    - name: Compare commits
      if: "${{ steps.commits.outputs.MAIN != steps.commits.outputs.TAG }}"
      uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
      with:
        script: |
            core.setFailed('Tagged commit does not match main')

  bump-version:
    runs-on: ubuntu-latest
    needs: [validate]
    env:
      VERSION: "${{ github.ref_name }}"
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: "main"
          ssh-key: "${{ secrets.SSH_KEY }}"
      - name: Update version
        run: python scripts/update_version.py "$GITHUB_REF_NAME"
      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a  #v4.16.0
        with:
          commit_message: Bump version to ${{ env.VERSION }} [skip ci]
          create_branch: true
          branch: release-${{ env.VERSION }}
      - name: Merge changes to main
        run: |
          git checkout "main"
          git merge "release-${{ env.VERSION }}" --no-edit
          git push

          git tag -f "$GITHUB_REF_NAME"
          git push -f origin "$GITHUB_REF_NAME"

  test:
    runs-on: ubuntu-latest
    needs: [bump-version]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest tox
    - name: Run tests
      run: |
        tox
