name: Bump version

on:
  workflow_dispatch:
    inputs:
      bump_type:
        type: choice
        description: Version bump type
        options:
        - patch
        - minor
        - major
        - override

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: github.event.inputs.bump_type != 'override'
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      - name: Run version bump script
        run: |
          echo "VERSION=$(python scripts/update_version.py ${{ github.event.inputs.bump_type }} )" >> "$GITHUB_ENV"
      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a  #v4.16.0
        with:
          commit_message: Bump version to ${{ env.VERSION }}
          create_branch: true
          branch: release-${{ env.VERSION }}
      - name: Merge changes to main
        run: |
          git checkout "main"
          git merge release-"$VERSION" --no-edit
          git push
      - name: Tag and push to main
        run: |
          git tag "$VERSION"
          git push origin "$VERSION"

  test:
    runs-on: ubuntu-latest
    needs: [bump-version]
    if: ${{ !failure() }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest tox
    - name: Run tests
      run: |
        tox
